// Generated by CoffeeScript 1.10.0
(function() {
  var cutoff, isInt, k, places, sign, step, sum;

  k = sign = 1;

  sum = 0;

  isInt = function(value) {
    var x;
    if (isNaN(value)) {
      return false;
    }
    x = parseFloat(value);
    return (x | 0) === x;
  };

  if (!isInt(process.argv[2])) {
    places = 2;
  } else {
    places = process.argv[2];
  }

  cutoff = 0.5 / Math.pow(12, places);

  while (true) {
    step = 4 * (Math.pow(2, k) + Math.pow(3, k)) / (Math.pow(6, k) * k);
    sum += sign * step;
    if (step < cutoff) {
      break;
    }
    k += 2;
    sign *= -1;
  }

  console.log(sum.toString(12).substring(0, +places + 2).replace('a', 'x').replace('b', 'ε'));

}).call(this);
