// Generated by CoffeeScript 1.10.0
(function() {
  var i, n, oneToAGross, say;

  say = function(x) {
    return console.log(x);
  };

  oneToAGross = [];

  for (n = i = 1; i <= 144; n = ++i) {
    oneToAGross[oneToAGross.length] = n.toString(12);
  }

  say(oneToAGross);

}).call(this);
