// Generated by CoffeeScript 1.10.0
(function() {
  const http = require('http');
  var requestCallback, server;

  requestCallback = function(req, res) {
    console.log(req.url);
    res.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    return res.end('okeedoky');
  };

  server = http.createServer(requestCallback);

  server.listen('3000', '127.0.0.1');

}).call(this);
