// Generated by CoffeeScript 1.10.0
(function() {
  var genNum, i, power, ref, totalGen, totalMW;

  totalGen = 19;

  totalMW = 0;

  power = 62;

  for (genNum = i = 1, ref = totalGen; 1 <= ref ? i <= ref : i >= ref; genNum = 1 <= ref ? ++i : --i) {
    if (genNum > 4) {
      power = 124;
    }
    if (genNum % 2) {
      console.log("Generator #" + genNum + " is off.");
    } else {
      totalMW += power;
      console.log("Generator #" + genNum + " is on, adding " + power + " MW, for a total of " + totalMW + " MW!");
    }
  }

}).call(this);
