// Generated by CoffeeScript 1.10.0
(function() {
  var count, i, monthNumber, monthsToPrint, numSheep, ref;

  numSheep = 4;

  monthsToPrint = 12;

  for (monthNumber = i = 1, ref = monthsToPrint; 1 <= ref ? i <= ref : i >= ref; monthNumber = 1 <= ref ? ++i : --i) {
    if (monthNumber % 4 === 0) {
      count = numSheep * 0.75;
      numSheep -= count;
      console.log("Removing " + count + " sheep from the population.");
    } else if (numSheep > 10000) {
      count = numSheep * 0.5;
      numSheep -= count;
      console.log("Removing " + count + " sheep from the population.");
    }
    numSheep *= 4;
    console.log("There will be " + numSheep + " sheep after " + monthNumber + " month(s)!");
  }

}).call(this);
