// Generated by CoffeeScript 1.10.0
(function() {
  var arg, i, len, ref;

  ref = process.argv.slice(2);
  for (i = 0, len = ref.length; i < len; i++) {
    arg = ref[i];
    console.log(arg.toLowerCase().slice(0, 3));
  }

}).call(this);
