// Generated by CoffeeScript 1.10.0
(function() {
  var bit, i, j, low, say;

  say = function(x) {
    return console.log(x);
  };

  low = function(x) {
    return x.toLowerCase();
  };

  bit = function(x) {
    return x.substring(0, 3);
  };

  for (i = j = 2; j <= 4; i = ++j) {
    say(low(bit(process.argv[i])));
  }

}).call(this);
