// Generated by CoffeeScript 1.10.0
(function() {
  var arg, args, bit, i, len, low, say;

  say = function(x) {
    return console.log(x);
  };

  low = function(x) {
    return x.toLowerCase();
  };

  bit = function(x) {
    return x.substring(0, 3);
  };

  args = process.argv.slice(2);

  for (i = 0, len = args.length; i < len; i++) {
    arg = args[i];
    say(low(bit(arg)));
  }

}).call(this);
