// Generated by CoffeeScript 1.10.0
(function() {
  var ar, b;

  ar = [1, 2, 3, 4, 5];

  (function(x) {
    return x[3] = 12;
  })(ar);

  console.log(ar);

  b = 12;

  (function(x) {
    return x = 1;
  })(b);

  console.log(b);

}).call(this);
