// Generated by CoffeeScript 1.10.0
(function() {
  var age, fizzBuzz, i, n, say;

  age = 1;

  say = function(x) {
    return console.log(x);
  };

  fizzBuzz = function(n) {
    if (!(n % 3 && n % 5)) {
      return say((n % 3 ? "" : "fizz") + (n % 15 ? "" : " ") + (n % 5 ? "" : "buzz"));
    }
  };

  for (n = i = 1; i <= 100; n = ++i) {
    fizzBuzz(n);
  }

}).call(this);
